name: Test Redmine Plugin

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.2]

    env:
      REDMINE_VER: 5.1-stable
      PLUGIN_NAME: vault
      REDMINE_GIT_REPO: git://github.com/redmine/redmine.git
      REDMINE_PATH: ${{ github.workspace }}/redmine
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Checkout redmine repo
        run: git clone --depth=1 --branch=$REDMINE_VER $REDMINE_GIT_REPO $REDMINE_PATH